servers:
  Mastiff:
    auth_token: "2j0ZXs82uJ78fmGVfSKxkQ26Nhl_2MiAUCneGVvY4BmQDLMya"
    domain: "vital-mastiff-publicly.ngrok-free.app"
    api: "2uBh0vcHjqPdwVi3t4gz9D9ZEH9_3R1frHq58vY8VQEzSuUMW"
    port: 8765

  Smoothly:
    auth_token: "2uaepshfgfXbFazHgLVrtGH1IsO_7ABTr6aEWtt6bZksmJf8h"
    domain: "smoothly-on-hyena.ngrok-free.app"
    api: "ak_2uafcx7VDVvaUvckKoEWawgK74O"
    port: 8766

  Faithful:
    auth_token: "2udPshjR6WsKGo77os4TjN5chmX_26Up9EChUALvx2j4y8fgF"
    domain: "next-boxer-faithful.ngrok-free.app"
    api: "2ue1ZKkjebeEIwvvDxXowlTvo3i_2uKULVDsyEo6A5prX7Gyg"
    port: 8767

sentence_checker_seuil: 0.8
game_duration: 150
canvas_height: 200
canvas_width: 200
points_per_found: 25

gif_ips: 16

fps: 50
refresh_drawing_time: 1

players_colors:
  - [255, 220, 220] # 1er - Rose pâle
  - [255, 230, 204] # 2e - Pêche clair
  - [255, 240, 180] # 3e - Jaune pastel
  - [220, 245, 200] # 4e - Vert menthe
  - [200, 235, 255] # 5e - Bleu ciel clair
  - [190, 210, 255] # 6e - Bleu lavande
  - [215, 190, 255] # 7e - Violet clair
  - [240, 190, 255] # 8e - Mauve pastel
  - [250, 200, 230] # 9e - Rose bonbon
  - [255, 210, 210] # 10e - Rose saumoné

drawing_colors:
  - [255, 0, 0] # Rouge
  - [0, 255, 0] # Vert
  - [0, 0, 255] # Bleu
  - [255, 255, 0] # Jaune
  - [255, 165, 0] # Orange
  - [128, 0, 128] # Violet
  - [0, 0, 0] # Noir
  - [255, 255, 255] # Blanc
  - [0, 255, 255] # Cyan
  - [255, 20, 147] # Rose vif
  - [139, 69, 19] # Marron
  - [128, 128, 128] # Gris

succeed_color: [99, 255, 108] #63ff6c
bad_color: [252, 100, 85] #fc6455
