sentence_checker_seuil: 0.75
game_duration: 60
canvas_height: 200
canvas_width: 200

game_page_fps: 50
refresh_drawing_time: 1

players_colors:
  - [255, 220, 220] # 1er - Rose pâle
  - [255, 230, 204] # 2e - Pêche clair
  - [255, 240, 180] # 3e - Jaune pastel
  - [220, 245, 200] # 4e - Vert menthe
  - [200, 235, 255] # 5e - Bleu ciel clair
  - [190, 210, 255] # 6e - Bleu lavande
  - [215, 190, 255] # 7e - Violet clair
  - [240, 190, 255] # 8e - Mauve pastel
  - [250, 200, 230] # 9e - Rose bonbon
  - [255, 210, 210] # 10e - Rose saumoné

drawing_colors:
  - [255, 0, 0] # Rouge
  - [0, 255, 0] # Vert
  - [0, 0, 255] # Bleu
  - [255, 255, 0] # Jaune
  - [255, 165, 0] # Orange
  - [128, 0, 128] # Violet
  - [0, 0, 0] # Noir
  - [255, 255, 255] # Blanc
  - [0, 255, 255] # Cyan
  - [255, 20, 147] # Rose vif
  - [139, 69, 19] # Marron
  - [128, 128, 128] # Gris
