sentence_checker_seuil: 0.75
canvas_height: 10
canvas_width: 10

players_colors:
  - [255, 220, 220] # 1er - Rose pâle
  - [255, 230, 204] # 2e - Pêche clair
  - [255, 240, 180] # 3e - Jaune pastel
  - [220, 245, 200] # 4e - Vert menthe
  - [200, 235, 255] # 5e - Bleu ciel clair
  - [190, 210, 255] # 6e - Bleu lavande
  - [215, 190, 255] # 7e - Violet clair
  - [240, 190, 255] # 8e - Mauve pastel
  - [250, 200, 230] # 9e - Rose bonbon
  - [255, 210, 210] # 10e - Rose saumoné
