import random

sujets = [
    "Un ninja",
    "Un dragon",
    "Un caméléon",
    "Un magicien",
    "Un robot",
    "Une sorcière",
    "Un lama",
    "Un astronaute",
    "Un poulpe",
    "Un espion",
    "Un vampire",
    "Un chien",
    "Un chat",
    "Un kangourou",
    "Un alien",
    "Un pirate",
    "Un cheval",
    "Un hibou",
    "Un dinosaure",
    "Un hamster",
    "Un perroquet",
    "Un pharaon",
    "Un monstre des marais",
    "Un cyclope",
    "Une fée",
    "Un yéti",
    "Un fantôme",
    "Un zombie",
    "Un gladiateur",
    "Un scientifique fou",
    "Un chevalier",
    "Un capitaine de bateau",
    "Un pingouin",
    "Un singe",
    "Un escargot",
    "Un avocat (le fruit et la profession!)",
    "Un cactus vivant",
    "Un marshmallow avec des bras",
    "Un cochon",
    "Un serpent",
    "Un kiwi",
    "Une étoile de mer",
    "Un iceberg",
    "Un brocoli",
    "Un ballon de foot vivant",
    "Une brique de lait",
    "Un poisson rouge",
    "Un hamburger vivant",
    "Un hot-dog qui parle",
    "Une chaussure avec des yeux",
    "Un robot aspirateur",
    "Une tasse de café avec un visage",
    "Un crabe danseur",
    "Un mouton en tenue de karaté",
    "Un bonhomme en pain d’épices",
    "Une carotte avec un chapeau",
    "Un rouleau de sushi qui marche",
    "Une guitare avec des jambes",
    "Un téléphone ",
    "Un avion en papier",
    "Une pizza",
    "Un éléphant",
    "Une girafe",
    "Un ours polaire",
    "Un kangourou boxeur",
    "Un caméléon invisible",
]

actions = [
    "qui fait du ski",
    "qui danse",
    "qui joue de la guitare",
    "qui fait du surf",
    "qui cuisine des crêpes",
    "qui jongle avec des poissons",
    "qui lance un avion en papier",
    "qui joue à cache-cache",
    "qui chante sous la douche",
    "qui escalade une montagne de bonbons",
    "qui fait du vélo sur l'eau",
    "qui marche sur un trampoline",
    "qui joue au basket",
    "qui peint un tableau",
    "qui joue aux échecs avec un fantôme",
    "qui fabrique une fusée en carton",
    "qui jongle avec des oranges",
    "qui essaie de réparer un robot",
    "qui pêche des étoiles filantes",
    "qui jongle avec des glaçons",
    "qui tue son miroir",
    "qui mange un gâteau géant",
    "qui saute en parachute avec un parapluie",
    "qui vole avec des ballons",
    "qui fait du patin à glace sur une banane",
    "qui joue du piano avec ses pieds",
    "qui construit un château en sable lunaire",
    "qui se bat contre son ombre",
    "qui rentre dans un frigo",
    "qui parle à une plante",
    "qui jongle avec des téléphones",
    "qui surf sur une vague",
    "qui fait un selfie avec un requin",
    "qui fait une bataille de polochons avec un squelette",
    "qui boit du thé avec une pieuvre",
    "qui court sur un arc-en-ciel",
    "qui fait une course de chameaux dans le désert",
    "qui tente de manger une pastèque entière",
    "qui se prend un éclair un éclair",
    "qui fait un duel au sabre avec Dark Vador",
    "qui joue au foot avec une pastèque",
    "qui dort sur un nuage",
    "qui fait une bataille de boules de neige avec un pingouin",
    "qui danse avec une méduse",
    "qui construit un château en spaghetti",
    "qui fait une course contre une tortue",
    "qui attrape une étoile",
    "qui lit un livre dans l’espace",
    "qui fait du trampoline sur la Lune",
]

def new_sentence():
    global sujets, actions, details

    sujet = random.choice(sujets)
    action = random.choice(actions)
    # detail = random.choice(details)
    sentence = f"{sujet} {action}"

    return sentence
