phrase = [
    "Un pingouin en rollers",
    "Un escargot avec un turbo",
    "Un poisson qui fait du karaté",
    "Un chat espion en mission secrète",
    "Un dinosaure qui joue au bowling",
    "Un éléphant sur un trampoline",
    "Une girafe avec un cou noué en nœud",
    "Un robot qui danse le moonwalk",
    "Un super-héros en pantoufles",
    "Un serpent qui joue à la corde à sauter",
    "Un pingouin en rollers qui fait du surf",
    "Un escargot avec un turbo qui saute en parachute",
    "Un poisson qui fait du karaté en mode ninja",
    "Un chat espion en mission secrète qui saute en parachute",
    "Un dinosaure qui joue au bowling qui mange une glace",
    "Un éléphant sur un trampoline sous la pluie",
    "Une girafe avec un cou noué en nœud en tutu",
    "Un robot qui danse le moonwalk dans une fusée",
    "Un super-héros en pantoufles en train de jongler",
    "Un serpent qui joue à la corde à sauter qui fait un selfie",
    "Un pingouin en rollers qui fait du surf",
    "Un escargot avec un turbo qui fait du surf",
    "Un poisson qui fait du karaté au sommet d'une montagne",
    "Un chat espion en mission secrète en train de jongler",
    "Un dinosaure qui joue au bowling qui joue de la guitare",
    "Un éléphant sur un trampoline avec un chapeau géant",
    "Une girafe avec un cou noué en nœud qui parle aux extraterrestres",
    "Un robot qui danse le moonwalk qui joue de la guitare",
    "Un super-héros en pantoufles qui vole avec des ballons",
    "Un serpent qui joue à la corde à sauter en train de jongler",
    "Un pingouin en rollers en mode ninja",
    "Un escargot avec un turbo en tutu",
    "Un poisson qui fait du karaté qui joue de la guitare",
    "Un chat espion en mission secrète qui saute en parachute",
    "Un dinosaure qui joue au bowling qui conduit une voiture minuscule",
    "Un éléphant sur un trampoline avec un chapeau géant",
    "Une girafe avec un cou noué en nœud en mode ninja",
    "Un robot qui danse le moonwalk sous la pluie",
    "Un super-héros en pantoufles sous la pluie",
    "Un serpent qui joue à la corde à sauter avec des lunettes de soleil",
    "Un pingouin en rollers qui mange une glace",
    "Un escargot avec un turbo sous la pluie",
    "Un poisson qui fait du karaté en mode ninja",
    "Un chat espion en mission secrète au sommet d'une montagne",
    "Un dinosaure qui joue au bowling dans une tasse de thé",
    "Un éléphant sur un trampoline dans une tasse de thé",
    "Une girafe avec un cou noué en nœud avec des lunettes de soleil",
    "Un robot qui danse le moonwalk qui fait un selfie",
    "Un super-héros en pantoufles avec une moustache",
    "Un serpent qui joue à la corde à sauter avec des lunettes de soleil",
    "Un pingouin en rollers qui conduit une voiture minuscule",
    "Un escargot avec un turbo sur un skateboard",
    "Un poisson qui fait du karaté qui fait du surf",
    "Un chat espion en mission secrète qui mange une glace",
    "Un dinosaure qui joue au bowling en tutu",
    "Un éléphant sur un trampoline avec un chapeau géant",
    "Une girafe avec un cou noué en nœud qui dort debout",
    "Un robot qui danse le moonwalk qui dort debout",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter qui fait du surf",
    "Un pingouin en rollers qui dort debout",
    "Un escargot avec un turbo qui parle aux extraterrestres",
    "Un poisson qui fait du karaté en mode ninja",
    "Un chat espion en mission secrète en tutu",
    "Un dinosaure qui joue au bowling qui saute en parachute",
    "Un éléphant sur un trampoline qui dort debout",
    "Une girafe avec un cou noué en nœud qui vole avec des ballons",
    "Un robot qui danse le moonwalk qui dort debout",
    "Un super-héros en pantoufles qui conduit une voiture minuscule",
    "Un serpent qui joue à la corde à sauter qui dort debout",
    "Un pingouin en rollers qui conduit une voiture minuscule",
    "Un escargot avec un turbo au sommet d'une montagne",
    "Un poisson qui fait du karaté qui fait un selfie",
    "Un chat espion en mission secrète qui dort debout",
    "Un dinosaure qui joue au bowling qui vole avec des ballons",
    "Un éléphant sur un trampoline avec des lunettes de soleil",
    "Une girafe avec un cou noué en nœud dans une fusée",
    "Un robot qui danse le moonwalk qui vole avec des ballons",
    "Un super-héros en pantoufles qui vole avec des ballons",
    "Un serpent qui joue à la corde à sauter qui parle aux extraterrestres",
    "Un pingouin en rollers en train de jongler",
    "Un escargot avec un turbo dans une fusée",
    "Un poisson qui fait du karaté dans une tasse de thé",
    "Un chat espion en mission secrète en mode ninja",
    "Un dinosaure qui joue au bowling en tutu",
    "Un éléphant sur un trampoline qui joue de la guitare",
    "Une girafe avec un cou noué en nœud qui mange une glace",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles qui mange une glace",
    "Un serpent qui joue à la corde à sauter qui vole avec des ballons",
    "Un pingouin en rollers qui mange une glace",
    "Un escargot avec un turbo qui conduit une voiture minuscule",
    "Un poisson qui fait du karaté qui joue de la guitare",
    "Un chat espion en mission secrète sur un skateboard",
    "Un dinosaure qui joue au bowling avec un chapeau géant",
    "Un éléphant sur un trampoline en train de jongler",
    "Une girafe avec un cou noué en nœud qui dort debout",
    "Un robot qui danse le moonwalk avec un chapeau géant",
    "Un super-héros en pantoufles dans une tasse de thé",
    "Un serpent qui joue à la corde à sauter qui parle aux extraterrestres",
    "Un pingouin en rollers sur un skateboard",
    "Un escargot avec un turbo qui mange une glace",
    "Un poisson qui fait du karaté qui fait du surf",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling avec un chapeau géant",
    "Un éléphant sur un trampoline qui mange une glace",
    "Une girafe avec un cou noué en nœud en train de jongler",
    "Un robot qui danse le moonwalk qui parle aux extraterrestres",
    "Un super-héros en pantoufles qui fait du surf",
    "Un serpent qui joue à la corde à sauter dans une fusée",
    "Un pingouin en rollers qui mange une glace",
    "Un escargot avec un turbo en tutu",
    "Un poisson qui fait du karaté qui joue de la guitare",
    "Un chat espion en mission secrète qui vole avec des ballons",
    "Un dinosaure qui joue au bowling qui vole avec des ballons",
    "Un éléphant sur un trampoline qui joue de la guitare",
    "Une girafe avec un cou noué en nœud qui vole avec des ballons",
    "Un robot qui danse le moonwalk qui joue de la guitare",
    "Un super-héros en pantoufles dans une tasse de thé",
    "Un serpent qui joue à la corde à sauter qui mange une glace",
    "Un pingouin en rollers en tutu",
    "Un escargot avec un turbo qui parle aux extraterrestres",
    "Un poisson qui fait du karaté qui joue de la guitare",
    "Un chat espion en mission secrète qui mange une glace",
    "Un dinosaure qui joue au bowling qui dort debout",
    "Un éléphant sur un trampoline en train de jongler",
    "Une girafe avec un cou noué en nœud dans une fusée",
    "Un robot qui danse le moonwalk qui fait un selfie",
    "Un super-héros en pantoufles en tutu",
    "Un serpent qui joue à la corde à sauter sur un skateboard",
    "Un pingouin en rollers qui fait un selfie",
    "Un escargot avec un turbo qui parle aux extraterrestres",
    "Un poisson qui fait du karaté avec un chapeau géant",
    "Un chat espion en mission secrète au sommet d'une montagne",
    "Un dinosaure qui joue au bowling en tutu",
    "Un éléphant sur un trampoline qui parle aux extraterrestres",
    "Une girafe avec un cou noué en nœud dans une fusée",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles dans une fusée",
    "Un serpent qui joue à la corde à sauter qui fait un selfie",
    "Un pingouin en rollers qui joue de la guitare",
    "Un escargot avec un turbo avec des lunettes de soleil",
    "Un poisson qui fait du karaté avec des lunettes de soleil",
    "Un chat espion en mission secrète sur un skateboard",
    "Un dinosaure qui joue au bowling dans une fusée",
    "Un éléphant sur un trampoline dans une fusée",
    "Une girafe avec un cou noué en nœud qui saute en parachute",
    "Un robot qui danse le moonwalk avec des lunettes de soleil",
    "Un super-héros en pantoufles qui saute en parachute",
    "Un serpent qui joue à la corde à sauter qui vole avec des ballons",
    "Un pingouin en rollers qui fait un selfie",
    "Un escargot avec un turbo qui saute en parachute",
    "Un poisson qui fait du karaté dans une tasse de thé",
    "Un chat espion en mission secrète qui joue de la guitare",
    "Un dinosaure qui joue au bowling sous la pluie",
    "Un éléphant sur un trampoline avec des lunettes de soleil",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles dans une tasse de thé",
    "Un serpent qui joue à la corde à sauter avec une moustache",
    "Un pingouin en rollers dans une tasse de thé",
    "Un escargot avec un turbo en mode ninja",
    "Un poisson qui fait du karaté qui parle aux extraterrestres",
    "Un chat espion en mission secrète avec un chapeau géant",
    "Un dinosaure qui joue au bowling en train de jongler",
    "Un éléphant sur un trampoline avec une moustache",
    "Une girafe avec un cou noué en nœud qui dort debout",
    "Un robot qui danse le moonwalk qui parle aux extraterrestres",
    "Un super-héros en pantoufles qui dort debout",
    "Un serpent qui joue à la corde à sauter qui fait du surf",
    "Un pingouin en rollers avec une moustache",
    "Un escargot avec un turbo qui mange une glace",
    "Un poisson qui fait du karaté en tutu",
    "Un chat espion en mission secrète au sommet d'une montagne",
    "Un dinosaure qui joue au bowling qui conduit une voiture minuscule",
    "Un éléphant sur un trampoline qui dort debout",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk dans une fusée",
    "Un super-héros en pantoufles qui mange une glace",
    "Un serpent qui joue à la corde à sauter dans une fusée",
    "Un pingouin en rollers qui fait un selfie",
    "Un escargot avec un turbo en train de jongler",
    "Un poisson qui fait du karaté sur un skateboard",
    "Un chat espion en mission secrète sur un skateboard",
    "Un dinosaure qui joue au bowling avec un chapeau géant",
    "Un éléphant sur un trampoline en mode ninja",
    "Une girafe avec un cou noué en nœud qui mange une glace",
    "Un robot qui danse le moonwalk dans une tasse de thé",
    "Un super-héros en pantoufles qui vole avec des ballons",
    "Un serpent qui joue à la corde à sauter en tutu",
    "Un pingouin en rollers sous la pluie",
    "Un escargot avec un turbo au sommet d'une montagne",
    "Un poisson qui fait du karaté qui fait du surf",
    "Un chat espion en mission secrète en tutu",
    "Un dinosaure qui joue au bowling dans une fusée",
    "Un éléphant sur un trampoline qui joue de la guitare",
    "Une girafe avec un cou noué en nœud en tutu",
    "Un robot qui danse le moonwalk qui fait un selfie",
    "Un super-héros en pantoufles qui vole avec des ballons",
    "Un serpent qui joue à la corde à sauter avec des lunettes de soleil",
    "Un pingouin en rollers qui fait du surf",
    "Un escargot avec un turbo qui dort debout",
    "Un poisson qui fait du karaté qui fait un selfie",
    "Un chat espion en mission secrète avec une moustache",
    "Un dinosaure qui joue au bowling qui fait un selfie",
    "Un éléphant sur un trampoline qui mange une glace",
    "Une girafe avec un cou noué en nœud en mode ninja",
    "Un robot qui danse le moonwalk avec un chapeau géant",
    "Un super-héros en pantoufles qui mange une glace",
    "Un serpent qui joue à la corde à sauter avec une moustache",
    "Un pingouin en rollers dans une tasse de thé",
    "Un escargot avec un turbo dans une tasse de thé",
    "Un poisson qui fait du karaté avec un chapeau géant",
    "Un chat espion en mission secrète dans une fusée",
    "Un dinosaure qui joue au bowling en tutu",
    "Un éléphant sur un trampoline avec une moustache",
    "Une girafe avec un cou noué en nœud qui vole avec des ballons",
    "Un robot qui danse le moonwalk sous la pluie",
    "Un super-héros en pantoufles avec une moustache",
    "Un serpent qui joue à la corde à sauter qui vole avec des ballons",
    "Un pingouin en rollers qui vole avec des ballons",
    "Un escargot avec un turbo qui parle aux extraterrestres",
    "Un poisson qui fait du karaté qui fait du surf",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling en train de jongler",
    "Un éléphant sur un trampoline au sommet d'une montagne",
    "Une girafe avec un cou noué en nœud dans une tasse de thé",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles sous la pluie",
    "Un serpent qui joue à la corde à sauter sous la pluie",
    "Un pingouin en rollers qui dort debout",
    "Un escargot avec un turbo qui fait un selfie",
    "Un poisson qui fait du karaté qui parle aux extraterrestres",
    "Un chat espion en mission secrète en train de jongler",
    "Un dinosaure qui joue au bowling sous la pluie",
    "Un éléphant sur un trampoline qui fait du surf",
    "Une girafe avec un cou noué en nœud qui fait du surf",
    "Un robot qui danse le moonwalk sous la pluie",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter sous la pluie",
    "Un pingouin en rollers avec des lunettes de soleil",
    "Un escargot avec un turbo qui joue de la guitare",
    "Un poisson qui fait du karaté qui saute en parachute",
    "Un chat espion en mission secrète qui dort debout",
    "Un dinosaure qui joue au bowling qui fait du surf",
    "Un éléphant sur un trampoline qui parle aux extraterrestres",
    "Une girafe avec un cou noué en nœud avec des lunettes de soleil",
    "Un robot qui danse le moonwalk qui vole avec des ballons",
    "Un super-héros en pantoufles qui vole avec des ballons",
    "Un serpent qui joue à la corde à sauter qui fait du surf",
    "Un pingouin en rollers qui fait un selfie",
    "Un escargot avec un turbo qui conduit une voiture minuscule",
    "Un poisson qui fait du karaté sur un skateboard",
    "Un chat espion en mission secrète dans une fusée",
    "Un dinosaure qui joue au bowling avec une moustache",
    "Un éléphant sur un trampoline qui parle aux extraterrestres",
    "Une girafe avec un cou noué en nœud qui parle aux extraterrestres",
    "Un robot qui danse le moonwalk en mode ninja",
    "Un super-héros en pantoufles en tutu",
    "Un serpent qui joue à la corde à sauter sous la pluie",
    "Un pingouin en rollers avec des lunettes de soleil",
    "Un escargot avec un turbo sous la pluie",
    "Un poisson qui fait du karaté qui joue de la guitare",
    "Un chat espion en mission secrète en tutu",
    "Un dinosaure qui joue au bowling sous la pluie",
    "Un éléphant sur un trampoline qui vole avec des ballons",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk avec des lunettes de soleil",
    "Un super-héros en pantoufles qui conduit une voiture minuscule",
    "Un serpent qui joue à la corde à sauter qui mange une glace",
    "Un pingouin en rollers en mode ninja",
    "Un escargot avec un turbo qui saute en parachute",
    "Un poisson qui fait du karaté qui parle aux extraterrestres",
    "Un chat espion en mission secrète dans une fusée",
    "Un dinosaure qui joue au bowling en tutu",
    "Un éléphant sur un trampoline qui saute en parachute",
    "Une girafe avec un cou noué en nœud avec une moustache",
    "Un robot qui danse le moonwalk au sommet d'une montagne",
    "Un super-héros en pantoufles avec une moustache",
    "Un serpent qui joue à la corde à sauter dans une tasse de thé",
    "Un pingouin en rollers avec des lunettes de soleil",
    "Un escargot avec un turbo au sommet d'une montagne",
    "Un poisson qui fait du karaté dans une tasse de thé",
    "Un chat espion en mission secrète en train de jongler",
    "Un dinosaure qui joue au bowling sous la pluie",
    "Un éléphant sur un trampoline qui fait un selfie",
    "Une girafe avec un cou noué en nœud en tutu",
    "Un robot qui danse le moonwalk qui dort debout",
    "Un super-héros en pantoufles au sommet d'une montagne",
    "Un serpent qui joue à la corde à sauter qui dort debout",
    "Un pingouin en rollers sous la pluie",
    "Un escargot avec un turbo au sommet d'une montagne",
    "Un poisson qui fait du karaté en tutu",
    "Un chat espion en mission secrète qui fait un selfie",
    "Un dinosaure qui joue au bowling qui mange une glace",
    "Un éléphant sur un trampoline dans une fusée",
    "Une girafe avec un cou noué en nœud avec des lunettes de soleil",
    "Un robot qui danse le moonwalk dans une tasse de thé",
    "Un super-héros en pantoufles qui dort debout",
    "Un serpent qui joue à la corde à sauter sous la pluie",
    "Un pingouin en rollers qui joue de la guitare",
    "Un escargot avec un turbo qui joue de la guitare",
    "Un poisson qui fait du karaté sous la pluie",
    "Un chat espion en mission secrète qui dort debout",
    "Un dinosaure qui joue au bowling qui dort debout",
    "Un éléphant sur un trampoline dans une tasse de thé",
    "Une girafe avec un cou noué en nœud sous la pluie",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles qui mange une glace",
    "Un serpent qui joue à la corde à sauter qui dort debout",
    "Un pingouin en rollers au sommet d'une montagne",
    "Un escargot avec un turbo dans une tasse de thé",
    "Un poisson qui fait du karaté sous la pluie",
    "Un chat espion en mission secrète en train de jongler",
    "Un dinosaure qui joue au bowling avec une moustache",
    "Un éléphant sur un trampoline qui joue de la guitare",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk en tutu",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter avec des lunettes de soleil",
    "Un pingouin en rollers en mode ninja",
    "Un escargot avec un turbo avec des lunettes de soleil",
    "Un poisson qui fait du karaté sous la pluie",
    "Un chat espion en mission secrète en mode ninja",
    "Un dinosaure qui joue au bowling sous la pluie",
    "Un éléphant sur un trampoline qui vole avec des ballons",
    "Une girafe avec un cou noué en nœud qui conduit une voiture minuscule",
    "Un robot qui danse le moonwalk dans une fusée",
    "Un super-héros en pantoufles qui mange une glace",
    "Un serpent qui joue à la corde à sauter en train de jongler",
    "Un pingouin en rollers qui joue de la guitare",
    "Un escargot avec un turbo avec des lunettes de soleil",
    "Un poisson qui fait du karaté en train de jongler",
    "Un chat espion en mission secrète qui mange une glace",
    "Un dinosaure qui joue au bowling en mode ninja",
    "Un éléphant sur un trampoline qui fait un selfie",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk avec un chapeau géant",
    "Un super-héros en pantoufles en mode ninja",
    "Un serpent qui joue à la corde à sauter au sommet d'une montagne",
    "Un pingouin en rollers au sommet d'une montagne",
    "Un escargot avec un turbo avec un chapeau géant",
    "Un poisson qui fait du karaté avec des lunettes de soleil",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling avec des lunettes de soleil",
    "Un éléphant sur un trampoline sur un skateboard",
    "Une girafe avec un cou noué en nœud dans une fusée",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles qui fait un selfie",
    "Un serpent qui joue à la corde à sauter qui conduit une voiture minuscule",
    "Un pingouin en rollers qui dort debout",
    "Un escargot avec un turbo qui joue de la guitare",
    "Un poisson qui fait du karaté en mode ninja",
    "Un chat espion en mission secrète avec un chapeau géant",
    "Un dinosaure qui joue au bowling qui dort debout",
    "Un éléphant sur un trampoline en train de jongler",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk qui dort debout",
    "Un super-héros en pantoufles qui conduit une voiture minuscule",
    "Un serpent qui joue à la corde à sauter qui conduit une voiture minuscule",
    "Un pingouin en rollers en tutu",
    "Un escargot avec un turbo avec des lunettes de soleil",
    "Un poisson qui fait du karaté en train de jongler",
    "Un chat espion en mission secrète dans une fusée",
    "Un dinosaure qui joue au bowling avec des lunettes de soleil",
    "Un éléphant sur un trampoline sur un skateboard",
    "Une girafe avec un cou noué en nœud dans une fusée",
    "Un robot qui danse le moonwalk qui saute en parachute",
    "Un super-héros en pantoufles qui fait du surf",
    "Un serpent qui joue à la corde à sauter sous la pluie",
    "Un pingouin en rollers avec une moustache",
    "Un escargot avec un turbo qui mange une glace",
    "Un poisson qui fait du karaté avec des lunettes de soleil",
    "Un chat espion en mission secrète qui parle aux extraterrestres",
    "Un dinosaure qui joue au bowling en tutu",
    "Un éléphant sur un trampoline en tutu",
    "Une girafe avec un cou noué en nœud sous la pluie",
    "Un robot qui danse le moonwalk au sommet d'une montagne",
    "Un super-héros en pantoufles avec des lunettes de soleil",
    "Un serpent qui joue à la corde à sauter en tutu",
    "Un pingouin en rollers qui dort debout",
    "Un escargot avec un turbo en train de jongler",
    "Un poisson qui fait du karaté avec une moustache",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling avec des lunettes de soleil",
    "Un éléphant sur un trampoline qui fait du surf",
    "Une girafe avec un cou noué en nœud sous la pluie",
    "Un robot qui danse le moonwalk qui dort debout",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter qui parle aux extraterrestres",
    "Un pingouin en rollers avec un chapeau géant",
    "Un escargot avec un turbo avec des lunettes de soleil",
    "Un poisson qui fait du karaté qui dort debout",
    "Un chat espion en mission secrète qui conduit une voiture minuscule",
    "Un dinosaure qui joue au bowling qui fait un selfie",
    "Un éléphant sur un trampoline qui mange une glace",
    "Une girafe avec un cou noué en nœud qui vole avec des ballons",
    "Un robot qui danse le moonwalk qui dort debout",
    "Un super-héros en pantoufles dans une fusée",
    "Un serpent qui joue à la corde à sauter sous la pluie",
    "Un pingouin en rollers qui joue de la guitare",
    "Un escargot avec un turbo dans une fusée",
    "Un poisson qui fait du karaté au sommet d'une montagne",
    "Un chat espion en mission secrète qui saute en parachute",
    "Un dinosaure qui joue au bowling en tutu",
    "Un éléphant sur un trampoline dans une fusée",
    "Une girafe avec un cou noué en nœud qui vole avec des ballons",
    "Un robot qui danse le moonwalk en tutu",
    "Un super-héros en pantoufles sur un skateboard",
    "Un serpent qui joue à la corde à sauter sur un skateboard",
    "Un pingouin en rollers au sommet d'une montagne",
    "Un escargot avec un turbo en tutu",
    "Un poisson qui fait du karaté en mode ninja",
    "Un chat espion en mission secrète en tutu",
    "Un dinosaure qui joue au bowling dans une tasse de thé",
    "Un éléphant sur un trampoline qui saute en parachute",
    "Une girafe avec un cou noué en nœud sur un skateboard",
    "Un robot qui danse le moonwalk avec un chapeau géant",
    "Un super-héros en pantoufles dans une fusée",
    "Un serpent qui joue à la corde à sauter qui saute en parachute",
    "Un pingouin en rollers au sommet d'une montagne",
    "Un escargot avec un turbo qui fait un selfie",
    "Un poisson qui fait du karaté avec une moustache",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling qui dort debout",
    "Un éléphant sur un trampoline qui vole avec des ballons",
    "Une girafe avec un cou noué en nœud avec une moustache",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles qui dort debout",
    "Un serpent qui joue à la corde à sauter sous la pluie",
    "Un pingouin en rollers qui saute en parachute",
    "Un escargot avec un turbo qui saute en parachute",
    "Un poisson qui fait du karaté en tutu",
    "Un chat espion en mission secrète avec une moustache",
    "Un dinosaure qui joue au bowling au sommet d'une montagne",
    "Un éléphant sur un trampoline sur un skateboard",
    "Une girafe avec un cou noué en nœud qui mange une glace",
    "Un robot qui danse le moonwalk sous la pluie",
    "Un super-héros en pantoufles qui joue de la guitare",
    "Un serpent qui joue à la corde à sauter en train de jongler",
    "Un pingouin en rollers qui fait un selfie",
    "Un escargot avec un turbo qui parle aux extraterrestres",
    "Un poisson qui fait du karaté dans une fusée",
    "Un chat espion en mission secrète qui parle aux extraterrestres",
    "Un dinosaure qui joue au bowling en mode ninja",
    "Un éléphant sur un trampoline qui fait du surf",
    "Une girafe avec un cou noué en nœud qui conduit une voiture minuscule",
    "Un robot qui danse le moonwalk en train de jongler",
    "Un super-héros en pantoufles qui conduit une voiture minuscule",
    "Un serpent qui joue à la corde à sauter avec des lunettes de soleil",
    "Un pingouin en rollers dans une fusée",
    "Un escargot avec un turbo avec un chapeau géant",
    "Un poisson qui fait du karaté dans une fusée",
    "Un chat espion en mission secrète dans une tasse de thé",
    "Un dinosaure qui joue au bowling qui mange une glace",
    "Un éléphant sur un trampoline avec un chapeau géant",
    "Une girafe avec un cou noué en nœud qui fait du surf",
    "Un robot qui danse le moonwalk qui saute en parachute",
    "Un super-héros en pantoufles dans une tasse de thé",
    "Un serpent qui joue à la corde à sauter qui dort debout",
    "Un pingouin en rollers sur un skateboard",
    "Un escargot avec un turbo qui fait un selfie",
    "Un poisson qui fait du karaté en train de jongler",
    "Un chat espion en mission secrète qui dort debout",
    "Un dinosaure qui joue au bowling qui mange une glace",
    "Un éléphant sur un trampoline qui joue de la guitare",
    "Une girafe avec un cou noué en nœud qui vole avec des ballons",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles qui dort debout",
    "Un serpent qui joue à la corde à sauter en tutu",
    "Un pingouin en rollers qui dort debout",
    "Un escargot avec un turbo qui fait du surf",
    "Un poisson qui fait du karaté dans une fusée",
    "Un chat espion en mission secrète avec un chapeau géant",
    "Un dinosaure qui joue au bowling en train de jongler",
    "Un éléphant sur un trampoline qui vole avec des ballons",
    "Une girafe avec un cou noué en nœud dans une tasse de thé",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter avec une moustache",
    "Un pingouin en rollers qui vole avec des ballons",
    "Un escargot avec un turbo sur un skateboard",
    "Un poisson qui fait du karaté qui fait du surf",
    "Un chat espion en mission secrète qui saute en parachute",
    "Un dinosaure qui joue au bowling avec une moustache",
    "Un éléphant sur un trampoline qui vole avec des ballons",
    "Une girafe avec un cou noué en nœud avec des lunettes de soleil",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles qui mange une glace",
    "Un serpent qui joue à la corde à sauter dans une fusée",
    "Un pingouin en rollers qui fait un selfie",
    "Un escargot avec un turbo en train de jongler",
    "Un poisson qui fait du karaté qui conduit une voiture minuscule",
    "Un chat espion en mission secrète qui parle aux extraterrestres",
    "Un dinosaure qui joue au bowling qui conduit une voiture minuscule",
    "Un éléphant sur un trampoline au sommet d'une montagne",
    "Une girafe avec un cou noué en nœud en tutu",
    "Un robot qui danse le moonwalk dans une fusée",
    "Un super-héros en pantoufles avec une moustache",
    "Un serpent qui joue à la corde à sauter qui fait du surf",
    "Un pingouin en rollers dans une tasse de thé",
    "Un escargot avec un turbo qui vole avec des ballons",
    "Un poisson qui fait du karaté sur un skateboard",
    "Un chat espion en mission secrète qui conduit une voiture minuscule",
    "Un dinosaure qui joue au bowling dans une tasse de thé",
    "Un éléphant sur un trampoline sur un skateboard",
    "Une girafe avec un cou noué en nœud sur un skateboard",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles qui joue de la guitare",
    "Un serpent qui joue à la corde à sauter avec des lunettes de soleil",
    "Un pingouin en rollers qui mange une glace",
    "Un escargot avec un turbo avec une moustache",
    "Un poisson qui fait du karaté qui fait du surf",
    "Un chat espion en mission secrète avec une moustache",
    "Un dinosaure qui joue au bowling en mode ninja",
    "Un éléphant sur un trampoline qui fait un selfie",
    "Une girafe avec un cou noué en nœud qui mange une glace",
    "Un robot qui danse le moonwalk au sommet d'une montagne",
    "Un super-héros en pantoufles dans une fusée",
    "Un serpent qui joue à la corde à sauter qui fait du surf",
    "Un pingouin en rollers dans une tasse de thé",
    "Un escargot avec un turbo au sommet d'une montagne",
    "Un poisson qui fait du karaté en train de jongler",
    "Un chat espion en mission secrète dans une fusée",
    "Un dinosaure qui joue au bowling en tutu",
    "Un éléphant sur un trampoline qui fait un selfie",
    "Une girafe avec un cou noué en nœud qui parle aux extraterrestres",
    "Un robot qui danse le moonwalk en mode ninja",
    "Un super-héros en pantoufles qui saute en parachute",
    "Un serpent qui joue à la corde à sauter qui mange une glace",
    "Un pingouin en rollers en tutu",
    "Un escargot avec un turbo au sommet d'une montagne",
    "Un poisson qui fait du karaté qui mange une glace",
    "Un chat espion en mission secrète dans une tasse de thé",
    "Un dinosaure qui joue au bowling en mode ninja",
    "Un éléphant sur un trampoline au sommet d'une montagne",
    "Une girafe avec un cou noué en nœud dans une tasse de thé",
    "Un robot qui danse le moonwalk avec des lunettes de soleil",
    "Un super-héros en pantoufles sur un skateboard",
    "Un serpent qui joue à la corde à sauter qui vole avec des ballons",
    "Un pingouin en rollers qui dort debout",
    "Un escargot avec un turbo qui vole avec des ballons",
    "Un poisson qui fait du karaté qui dort debout",
    "Un chat espion en mission secrète qui fait un selfie",
    "Un dinosaure qui joue au bowling au sommet d'une montagne",
    "Un éléphant sur un trampoline sous la pluie",
    "Une girafe avec un cou noué en nœud avec un chapeau géant",
    "Un robot qui danse le moonwalk qui vole avec des ballons",
    "Un super-héros en pantoufles avec une moustache",
    "Un serpent qui joue à la corde à sauter sur un skateboard",
    "Un pingouin en rollers avec un chapeau géant",
    "Un escargot avec un turbo en train de jongler",
    "Un poisson qui fait du karaté avec une moustache",
    "Un chat espion en mission secrète qui parle aux extraterrestres",
    "Un dinosaure qui joue au bowling dans une tasse de thé",
    "Un éléphant sur un trampoline sur un skateboard",
    "Une girafe avec un cou noué en nœud qui mange une glace",
    "Un robot qui danse le moonwalk en train de jongler",
    "Un super-héros en pantoufles qui fait du surf",
    "Un serpent qui joue à la corde à sauter qui conduit une voiture minuscule",
    "Un pingouin en rollers qui dort debout",
    "Un escargot avec un turbo dans une tasse de thé",
    "Un poisson qui fait du karaté en train de jongler",
    "Un chat espion en mission secrète qui parle aux extraterrestres",
    "Un dinosaure qui joue au bowling dans une fusée",
    "Un éléphant sur un trampoline avec une moustache",
    "Une girafe avec un cou noué en nœud avec une moustache",
    "Un robot qui danse le moonwalk qui joue de la guitare",
    "Un super-héros en pantoufles avec une moustache",
    "Un serpent qui joue à la corde à sauter qui mange une glace",
    "Un pingouin en rollers dans une fusée",
    "Un escargot avec un turbo sur un skateboard",
    "Un poisson qui fait du karaté sur un skateboard",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling qui joue de la guitare",
    "Un éléphant sur un trampoline dans une fusée",
    "Une girafe avec un cou noué en nœud sur un skateboard",
    "Un robot qui danse le moonwalk qui fait du surf",
    "Un super-héros en pantoufles qui saute en parachute",
    "Un serpent qui joue à la corde à sauter qui mange une glace",
    "Un pingouin en rollers qui parle aux extraterrestres",
    "Un escargot avec un turbo en mode ninja",
    "Un poisson qui fait du karaté sur un skateboard",
    "Un chat espion en mission secrète dans une tasse de thé",
    "Un dinosaure qui joue au bowling dans une tasse de thé",
    "Un éléphant sur un trampoline qui conduit une voiture minuscule",
    "Une girafe avec un cou noué en nœud qui conduit une voiture minuscule",
    "Un robot qui danse le moonwalk qui conduit une voiture minuscule",
    "Un super-héros en pantoufles qui fait du surf",
    "Un serpent qui joue à la corde à sauter avec des lunettes de soleil",
    "Un pingouin en rollers avec une moustache",
    "Un escargot avec un turbo qui fait du surf",
    "Un poisson qui fait du karaté qui parle aux extraterrestres",
    "Un chat espion en mission secrète qui parle aux extraterrestres",
    "Un dinosaure qui joue au bowling sous la pluie",
    "Un éléphant sur un trampoline au sommet d'une montagne",
    "Une girafe avec un cou noué en nœud en mode ninja",
    "Un robot qui danse le moonwalk au sommet d'une montagne",
    "Un super-héros en pantoufles qui dort debout",
    "Un serpent qui joue à la corde à sauter en train de jongler",
    "Un pingouin en rollers qui joue de la guitare",
    "Un escargot avec un turbo qui fait un selfie",
    "Un poisson qui fait du karaté au sommet d'une montagne",
    "Un chat espion en mission secrète en mode ninja",
    "Un dinosaure qui joue au bowling avec un chapeau géant",
    "Un éléphant sur un trampoline qui dort debout",
    "Une girafe avec un cou noué en nœud avec des lunettes de soleil",
    "Un robot qui danse le moonwalk au sommet d'une montagne",
    "Un super-héros en pantoufles qui fait un selfie",
    "Un serpent qui joue à la corde à sauter qui conduit une voiture minuscule",
    "Un pingouin en rollers au sommet d'une montagne",
    "Un escargot avec un turbo avec un chapeau géant",
    "Un poisson qui fait du karaté sur un skateboard",
    "Un chat espion en mission secrète en mode ninja",
    "Un dinosaure qui joue au bowling dans une fusée",
    "Un éléphant sur un trampoline avec des lunettes de soleil",
    "Une girafe avec un cou noué en nœud qui conduit une voiture minuscule",
    "Un robot qui danse le moonwalk qui joue de la guitare",
    "Un super-héros en pantoufles qui vole avec des ballons",
    "Un serpent qui joue à la corde à sauter dans une tasse de thé",
    "Un pingouin en rollers qui joue de la guitare",
    "Un escargot avec un turbo avec des lunettes de soleil",
    "Un poisson qui fait du karaté qui mange une glace",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling dans une fusée",
    "Un éléphant sur un trampoline qui mange une glace",
    "Une girafe avec un cou noué en nœud qui dort debout",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles qui dort debout",
    "Un serpent qui joue à la corde à sauter qui saute en parachute",
    "Un pingouin en rollers qui fait un selfie",
    "Un escargot avec un turbo qui mange une glace",
    "Un poisson qui fait du karaté qui saute en parachute",
    "Un chat espion en mission secrète qui fait un selfie",
    "Un dinosaure qui joue au bowling qui joue de la guitare",
    "Un éléphant sur un trampoline qui parle aux extraterrestres",
    "Une girafe avec un cou noué en nœud qui parle aux extraterrestres",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles dans une tasse de thé",
    "Un serpent qui joue à la corde à sauter en tutu",
    "Un pingouin en rollers qui vole avec des ballons",
    "Un escargot avec un turbo en mode ninja",
    "Un poisson qui fait du karaté qui conduit une voiture minuscule",
    "Un chat espion en mission secrète avec une moustache",
    "Un dinosaure qui joue au bowling en mode ninja",
    "Un éléphant sur un trampoline en train de jongler",
    "Une girafe avec un cou noué en nœud avec un chapeau géant",
    "Un robot qui danse le moonwalk qui vole avec des ballons",
    "Un super-héros en pantoufles en tutu",
    "Un serpent qui joue à la corde à sauter qui mange une glace",
    "Un pingouin en rollers qui vole avec des ballons",
    "Un escargot avec un turbo au sommet d'une montagne",
    "Un poisson qui fait du karaté qui fait du surf",
    "Un chat espion en mission secrète en mode ninja",
    "Un dinosaure qui joue au bowling qui mange une glace",
    "Un éléphant sur un trampoline avec une moustache",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter dans une fusée",
    "Un pingouin en rollers qui joue de la guitare",
    "Un escargot avec un turbo qui fait du surf",
    "Un poisson qui fait du karaté en train de jongler",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling sur un skateboard",
    "Un éléphant sur un trampoline en tutu",
    "Une girafe avec un cou noué en nœud dans une fusée",
    "Un robot qui danse le moonwalk qui dort debout",
    "Un super-héros en pantoufles avec des lunettes de soleil",
    "Un serpent qui joue à la corde à sauter qui fait du surf",
    "Un pingouin en rollers dans une tasse de thé",
    "Un escargot avec un turbo en train de jongler",
    "Un poisson qui fait du karaté sur un skateboard",
    "Un chat espion en mission secrète au sommet d'une montagne",
    "Un dinosaure qui joue au bowling qui mange une glace",
    "Un éléphant sur un trampoline avec un chapeau géant",
    "Une girafe avec un cou noué en nœud dans une tasse de thé",
    "Un robot qui danse le moonwalk dans une fusée",
    "Un super-héros en pantoufles dans une tasse de thé",
    "Un serpent qui joue à la corde à sauter qui conduit une voiture minuscule",
    "Un pingouin en rollers qui fait du surf",
    "Un escargot avec un turbo qui saute en parachute",
    "Un poisson qui fait du karaté qui fait du surf",
    "Un chat espion en mission secrète qui dort debout",
    "Un dinosaure qui joue au bowling dans une tasse de thé",
    "Un éléphant sur un trampoline qui mange une glace",
    "Une girafe avec un cou noué en nœud sous la pluie",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter dans une tasse de thé",
    "Un pingouin en rollers avec des lunettes de soleil",
    "Un escargot avec un turbo sous la pluie",
    "Un poisson qui fait du karaté dans une fusée",
    "Un chat espion en mission secrète qui saute en parachute",
    "Un dinosaure qui joue au bowling qui fait un selfie",
    "Un éléphant sur un trampoline qui joue de la guitare",
    "Une girafe avec un cou noué en nœud dans une tasse de thé",
    "Un robot qui danse le moonwalk qui mange une glace",
    "Un super-héros en pantoufles qui saute en parachute",
    "Un serpent qui joue à la corde à sauter avec un chapeau géant",
    "Un pingouin en rollers qui parle aux extraterrestres",
    "Un escargot avec un turbo qui dort debout",
    "Un poisson qui fait du karaté en mode ninja",
    "Un chat espion en mission secrète en mode ninja",
    "Un dinosaure qui joue au bowling qui joue de la guitare",
    "Un éléphant sur un trampoline sur un skateboard",
    "Une girafe avec un cou noué en nœud dans une fusée",
    "Un robot qui danse le moonwalk qui fait un selfie",
    "Un super-héros en pantoufles qui dort debout",
    "Un serpent qui joue à la corde à sauter sur un skateboard",
    "Un pingouin en rollers dans une tasse de thé",
    "Un escargot avec un turbo en train de jongler",
    "Un poisson qui fait du karaté qui saute en parachute",
    "Un chat espion en mission secrète avec une moustache",
    "Un dinosaure qui joue au bowling au sommet d'une montagne",
    "Un éléphant sur un trampoline avec une moustache",
    "Une girafe avec un cou noué en nœud dans une fusée",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles en mode ninja",
    "Un serpent qui joue à la corde à sauter en mode ninja",
    "Un pingouin en rollers avec un chapeau géant",
    "Un escargot avec un turbo qui vole avec des ballons",
    "Un poisson qui fait du karaté qui fait un selfie",
    "Un chat espion en mission secrète qui mange une glace",
    "Un dinosaure qui joue au bowling qui joue de la guitare",
    "Un éléphant sur un trampoline dans une fusée",
    "Une girafe avec un cou noué en nœud qui saute en parachute",
    "Un robot qui danse le moonwalk qui parle aux extraterrestres",
    "Un super-héros en pantoufles dans une tasse de thé",
    "Un serpent qui joue à la corde à sauter au sommet d'une montagne",
    "Un pingouin en rollers qui vole avec des ballons",
    "Un escargot avec un turbo qui dort debout",
    "Un poisson qui fait du karaté qui conduit une voiture minuscule",
    "Un chat espion en mission secrète sous la pluie",
    "Un dinosaure qui joue au bowling qui fait du surf",
    "Un éléphant sur un trampoline en train de jongler",
    "Une girafe avec un cou noué en nœud dans une tasse de thé",
    "Un robot qui danse le moonwalk en tutu",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter dans une fusée",
    "Un pingouin en rollers qui dort debout",
    "Un escargot avec un turbo avec un chapeau géant",
    "Un poisson qui fait du karaté qui dort debout",
    "Un chat espion en mission secrète qui vole avec des ballons",
    "Un dinosaure qui joue au bowling qui dort debout",
    "Un éléphant sur un trampoline avec une moustache",
    "Une girafe avec un cou noué en nœud sur un skateboard",
    "Un robot qui danse le moonwalk qui mange une glace",
    "Un super-héros en pantoufles qui saute en parachute",
    "Un serpent qui joue à la corde à sauter avec des lunettes de soleil",
    "Un pingouin en rollers sur un skateboard",
    "Un escargot avec un turbo avec un chapeau géant",
    "Un poisson qui fait du karaté qui parle aux extraterrestres",
    "Un chat espion en mission secrète qui mange une glace",
    "Un dinosaure qui joue au bowling en mode ninja",
    "Un éléphant sur un trampoline au sommet d'une montagne",
    "Une girafe avec un cou noué en nœud qui vole avec des ballons",
    "Un robot qui danse le moonwalk dans une tasse de thé",
    "Un super-héros en pantoufles qui parle aux extraterrestres",
    "Un serpent qui joue à la corde à sauter au sommet d'une montagne",
    "Un pingouin en rollers au sommet d'une montagne",
    "Un escargot avec un turbo dans une fusée",
    "Un poisson qui fait du karaté en mode ninja",
    "Un chat espion en mission secrète dans une tasse de thé",
    "Un dinosaure qui joue au bowling dans une tasse de thé",
    "Un éléphant sur un trampoline avec un chapeau géant",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk sur un skateboard",
    "Un super-héros en pantoufles qui saute en parachute",
    "Un serpent qui joue à la corde à sauter au sommet d'une montagne",
    "Un pingouin en rollers qui fait du surf",
    "Un escargot avec un turbo dans une fusée",
    "Un poisson qui fait du karaté qui dort debout",
    "Un chat espion en mission secrète dans une tasse de thé",
    "Un dinosaure qui joue au bowling avec une moustache",
    "Un éléphant sur un trampoline qui parle aux extraterrestres",
    "Une girafe avec un cou noué en nœud en tutu",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter qui fait un selfie",
    "Un pingouin en rollers qui parle aux extraterrestres",
    "Un escargot avec un turbo dans une tasse de thé",
    "Un poisson qui fait du karaté dans une tasse de thé",
    "Un chat espion en mission secrète avec un chapeau géant",
    "Un dinosaure qui joue au bowling en mode ninja",
    "Un éléphant sur un trampoline sur un skateboard",
    "Une girafe avec un cou noué en nœud qui dort debout",
    "Un robot qui danse le moonwalk qui fait un selfie",
    "Un super-héros en pantoufles qui fait du surf",
    "Un serpent qui joue à la corde à sauter en tutu",
    "Un pingouin en rollers avec des lunettes de soleil",
    "Un escargot avec un turbo qui vole avec des ballons",
    "Un poisson qui fait du karaté avec des lunettes de soleil",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling avec un chapeau géant",
    "Un éléphant sur un trampoline qui conduit une voiture minuscule",
    "Une girafe avec un cou noué en nœud au sommet d'une montagne",
    "Un robot qui danse le moonwalk qui fait du surf",
    "Un super-héros en pantoufles qui parle aux extraterrestres",
    "Un serpent qui joue à la corde à sauter en train de jongler",
    "Un pingouin en rollers dans une tasse de thé",
    "Un escargot avec un turbo qui parle aux extraterrestres",
    "Un poisson qui fait du karaté en train de jongler",
    "Un chat espion en mission secrète sur un skateboard",
    "Un dinosaure qui joue au bowling sous la pluie",
    "Un éléphant sur un trampoline qui vole avec des ballons",
    "Une girafe avec un cou noué en nœud qui fait du surf",
    "Un robot qui danse le moonwalk qui joue de la guitare",
    "Un super-héros en pantoufles qui conduit une voiture minuscule",
    "Un serpent qui joue à la corde à sauter avec une moustache",
    "Un pingouin en rollers qui vole avec des ballons",
    "Un escargot avec un turbo qui vole avec des ballons",
    "Un poisson qui fait du karaté qui vole avec des ballons",
    "Un chat espion en mission secrète qui parle aux extraterrestres",
    "Un dinosaure qui joue au bowling qui dort debout",
    "Un éléphant sur un trampoline qui dort debout",
    "Une girafe avec un cou noué en nœud au sommet d'une montagne",
    "Un robot qui danse le moonwalk avec un chapeau géant",
    "Un super-héros en pantoufles sur un skateboard",
    "Un serpent qui joue à la corde à sauter sous la pluie",
    "Un pingouin en rollers sous la pluie",
    "Un escargot avec un turbo avec une moustache",
    "Un poisson qui fait du karaté qui vole avec des ballons",
    "Un chat espion en mission secrète qui parle aux extraterrestres",
    "Un dinosaure qui joue au bowling qui mange une glace",
    "Un éléphant sur un trampoline qui fait un selfie",
    "Une girafe avec un cou noué en nœud dans une fusée",
    "Un robot qui danse le moonwalk qui vole avec des ballons",
    "Un super-héros en pantoufles qui joue de la guitare",
    "Un serpent qui joue à la corde à sauter en train de jongler",
    "Un pingouin en rollers qui fait du surf",
    "Un escargot avec un turbo avec une moustache",
    "Un poisson qui fait du karaté en tutu",
    "Un chat espion en mission secrète sous la pluie",
    "Un dinosaure qui joue au bowling qui saute en parachute",
    "Un éléphant sur un trampoline qui saute en parachute",
    "Une girafe avec un cou noué en nœud en train de jongler",
    "Un robot qui danse le moonwalk en tutu",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter avec un chapeau géant",
    "Un pingouin en rollers qui vole avec des ballons",
    "Un escargot avec un turbo avec un chapeau géant",
    "Un poisson qui fait du karaté dans une tasse de thé",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling avec un chapeau géant",
    "Un éléphant sur un trampoline qui saute en parachute",
    "Une girafe avec un cou noué en nœud en train de jongler",
    "Un robot qui danse le moonwalk sous la pluie",
    "Un super-héros en pantoufles dans une fusée",
    "Un serpent qui joue à la corde à sauter qui vole avec des ballons",
    "Un pingouin en rollers avec des lunettes de soleil",
    "Un escargot avec un turbo qui dort debout",
    "Un poisson qui fait du karaté qui fait un selfie",
    "Un chat espion en mission secrète en train de jongler",
    "Un dinosaure qui joue au bowling qui fait du surf",
    "Un éléphant sur un trampoline sur un skateboard",
    "Une girafe avec un cou noué en nœud qui joue de la guitare",
    "Un robot qui danse le moonwalk dans une fusée",
    "Un super-héros en pantoufles en train de jongler",
    "Un serpent qui joue à la corde à sauter avec un chapeau géant",
    "Un pingouin en rollers au sommet d'une montagne",
    "Un escargot avec un turbo qui fait du surf",
    "Un poisson qui fait du karaté qui joue de la guitare",
    "Un chat espion en mission secrète avec une moustache",
    "Un dinosaure qui joue au bowling dans une fusée",
    "Un éléphant sur un trampoline qui conduit une voiture minuscule",
    "Une girafe avec un cou noué en nœud avec une moustache",
    "Un robot qui danse le moonwalk sous la pluie",
    "Un super-héros en pantoufles qui parle aux extraterrestres",
    "Un serpent qui joue à la corde à sauter avec une moustache",
    "Un pingouin en rollers sur un skateboard",
    "Un escargot avec un turbo qui fait un selfie",
    "Un poisson qui fait du karaté en tutu",
    "Un chat espion en mission secrète qui conduit une voiture minuscule",
    "Un dinosaure qui joue au bowling sur un skateboard",
    "Un éléphant sur un trampoline qui fait un selfie",
    "Une girafe avec un cou noué en nœud qui conduit une voiture minuscule",
    "Un robot qui danse le moonwalk en tutu",
    "Un super-héros en pantoufles dans une fusée",
    "Un serpent qui joue à la corde à sauter qui vole avec des ballons",
    "Un pingouin en rollers qui saute en parachute",
    "Un escargot avec un turbo sous la pluie",
    "Un poisson qui fait du karaté qui fait du surf",
    "Un chat espion en mission secrète sur un skateboard",
    "Un dinosaure qui joue au bowling qui fait un selfie",
    "Un éléphant sur un trampoline qui fait du surf",
    "Une girafe avec un cou noué en nœud sur un skateboard",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles dans une fusée",
    "Un serpent qui joue à la corde à sauter avec des lunettes de soleil",
    "Un pingouin en rollers sous la pluie",
    "Un escargot avec un turbo qui conduit une voiture minuscule",
    "Un poisson qui fait du karaté au sommet d'une montagne",
    "Un chat espion en mission secrète en tutu",
    "Un dinosaure qui joue au bowling qui conduit une voiture minuscule",
    "Un éléphant sur un trampoline qui saute en parachute",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk qui dort debout",
    "Un super-héros en pantoufles qui vole avec des ballons",
    "Un serpent qui joue à la corde à sauter qui saute en parachute",
    "Un pingouin en rollers qui fait un selfie",
    "Un escargot avec un turbo avec une moustache",
    "Un poisson qui fait du karaté au sommet d'une montagne",
    "Un chat espion en mission secrète qui fait un selfie",
    "Un dinosaure qui joue au bowling avec des lunettes de soleil",
    "Un éléphant sur un trampoline qui parle aux extraterrestres",
    "Une girafe avec un cou noué en nœud qui joue de la guitare",
    "Un robot qui danse le moonwalk avec une moustache",
    "Un super-héros en pantoufles qui fait un selfie",
    "Un serpent qui joue à la corde à sauter sur un skateboard",
    "Un pingouin en rollers avec un chapeau géant",
    "Un escargot avec un turbo dans une fusée",
    "Un poisson qui fait du karaté avec un chapeau géant",
    "Un chat espion en mission secrète avec une moustache",
    "Un dinosaure qui joue au bowling qui parle aux extraterrestres",
    "Un éléphant sur un trampoline qui vole avec des ballons",
    "Une girafe avec un cou noué en nœud avec des lunettes de soleil",
    "Un robot qui danse le moonwalk en train de jongler",
    "Un super-héros en pantoufles qui mange une glace",
    "Un serpent qui joue à la corde à sauter qui joue de la guitare",
    "Un pingouin en rollers qui fait un selfie",
    "Un escargot avec un turbo qui fait un selfie",
    "Un poisson qui fait du karaté avec une moustache",
    "Un chat espion en mission secrète avec des lunettes de soleil",
    "Un dinosaure qui joue au bowling sous la pluie",
    "Un éléphant sur un trampoline en tutu",
    "Une girafe avec un cou noué en nœud qui vole avec des ballons",
    "Un robot qui danse le moonwalk sous la pluie",
    "Un super-héros en pantoufles qui vole avec des ballons",
    "Un serpent qui joue à la corde à sauter qui conduit une voiture minuscule",
    "Un pingouin en rollers au sommet d'une montagne",
    "Un escargot avec un turbo au sommet d'une montagne",
    "Un poisson qui fait du karaté qui joue de la guitare",
    "Un chat espion en mission secrète avec une moustache",
    "Un dinosaure qui joue au bowling en mode ninja",
    "Un éléphant sur un trampoline dans une fusée",
    "Une girafe avec un cou noué en nœud qui conduit une voiture minuscule",
    "Un robot qui danse le moonwalk qui joue de la guitare",
    "Un super-héros en pantoufles qui joue de la guitare",
    "Un serpent qui joue à la corde à sauter avec une moustache",
    "Un pingouin en rollers qui conduit une voiture minuscule",
    "Un escargot avec un turbo en train de jongler",
    "Un poisson qui fait du karaté qui conduit une voiture minuscule",
    "Un chat espion en mission secrète en mode ninja",
    "Un dinosaure qui joue au bowling dans une tasse de thé",
    "Un éléphant sur un trampoline qui vole avec des ballons",
    "Une girafe avec un cou noué en nœud qui fait un selfie",
    "Un robot qui danse le moonwalk qui vole avec des ballons",
    "Un super-héros en pantoufles qui vole avec des ballons",
    "Un serpent qui joue à la corde à sauter qui parle aux extraterrestres",
    "Un pingouin en rollers en train de jongler",
    "Un escargot avec un turbo qui joue de la guitare",
    "Un poisson qui fait du karaté qui mange une glace",
    "Un chat espion en mission secrète qui mange une glace",
    "Un dinosaure qui joue au bowling qui dort debout",
    "Un éléphant sur un trampoline qui saute en parachute",
    "Une girafe avec un cou noué en nœud en train de jongler",
    "Un robot qui danse le moonwalk qui conduit une voiture minuscule",
    "Un super-héros en pantoufles sur un skateboard",
    "Un serpent qui joue à la corde à sauter qui conduit une voiture minuscule",
    "Un pingouin en rollers en tutu",
    "Un escargot avec un turbo sur un skateboard",
    "Un poisson qui fait du karaté sous la pluie",
    "Un chat espion en mission secrète dans une fusée",
    "Un dinosaure qui joue au bowling sur un skateboard",
    "Un éléphant sur un trampoline en mode ninja",
    "Une girafe avec un cou noué en nœud qui parle aux extraterrestres",
    "Un robot qui danse le moonwalk qui conduit une voiture minuscule",
    "Un super-héros en pantoufles qui joue de la guitare",
    "Un serpent qui joue à la corde à sauter sur un skateboard",
    "Un pingouin en rollers dans une fusée",
    "Un escargot avec un turbo avec un chapeau géant",
    "Un poisson qui fait du karaté avec une moustache",
    "Un chat espion en mission secrète dans une tasse de thé",
    "Un dinosaure qui joue au bowling en tutu",
    "Un éléphant sur un trampoline qui parle aux extraterrestres",
    "Une girafe avec un cou noué en nœud au sommet d'une montagne",
    "Un robot qui danse le moonwalk qui vole avec des ballons",
    "Un super-héros en pantoufles sous la pluie",
    "Un serpent qui joue à la corde à sauter sur un skateboard",
    "Un pingouin en rollers qui joue de la guitare",
    "Un escargot avec un turbo qui fait du surf",
    "Un poisson qui fait du karaté qui mange une glace",
    "Un chat espion en mission secrète avec un chapeau géant",
    "Un dinosaure qui joue au bowling sous la pluie",
    "Un éléphant sur un trampoline qui dort debout",
    "Une girafe avec un cou noué en nœud avec un chapeau géant",
    "Un robot qui danse le moonwalk qui fait un selfie",
    "Un super-héros en pantoufles avec un chapeau géant",
    "Un serpent qui joue à la corde à sauter qui mange une glace",
    "Un pingouin en rollers qui saute en parachute",
    "Un escargot avec un turbo sur un skateboard",
    "Un poisson qui fait du karaté avec des lunettes de soleil",
    "Un chat espion en mission secrète dans une fusée",
    "Un dinosaure qui joue au bowling qui dort debout",
    "Un éléphant sur un trampoline dans une fusée",
    "Une girafe avec un cou noué en nœud qui dort debout",
    "Un robot qui danse le moonwalk qui saute en parachute",
    "Un super-héros en pantoufles sur un skateboard",
    "Un serpent qui joue à la corde à sauter qui fait du surf"]
compteur = 0
test2 = 0
test3 = 20000
phrased = ""
phrases = []
for i in range(len(phrase)):
    compteur += len(phrase[i])
    test = len(phrase[i])
    if test < 24:
        test2 = test
        phrases.append(phrase[i])
    if test < test3:
        test3 = test
        phrased = phrase[i]
print(compteur / 1000)  # moyenne des phrases
print(test2)  # phrase la plus longue
print(test3)  # phrase la plus courte
print(phrased)
print(phrases)
